apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-loki
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: {{ .Values.destination.namespace }}
    server: {{ .Values.destination.server }}
  source:
    path: ''
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: {{ .Values.loki.source.targetRevision }}
    chart: loki
    helm:
      values: |-
        {{- toYaml .Values.loki.values | nindent 8 }}
  sources: []
  project: {{ .Values.project }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - Replace=true
      - PruneLast=true