image:
  tag: "INFRA-82-add-github-workflow-and-helm-chart-b1e0a27"
  pullPolicy: Always

ui:
  enabled: true
  image:
    tag: "INFRA-82-add-github-workflow-and-helm-chart-b1e0a27"
    pullPolicy: Always
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: bench.ai-nh-dev.privateai.kaops.dev
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - bench.ai-nh-dev.privateai.kaops.dev
        secretName: nh-ai-benchmark-ui-tls

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: bench-api.ai-nh-dev.privateai.kaops.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - bench-api.ai-nh-dev.privateai.kaops.dev
      secretName: nh-ai-benchmark-api-tls

secretName: "nh-ai-benchmark-secrets"

env:
  OI_BASE_URL: "http://open-webui.nh-addons.svc.cluster.local"
  OPEN_WEBUI_UID: "9300adce-b460-4cba-9167-d53ab4bce06e"
  RAG_BASE_URL: "http://ai-nh-dev-private-ai-rag-nh-rag-api.nh-addons.svc.cluster.local:8000"
  PIPELINES_BASE_URL: "http://open-webui-pipelines.nh-addons.svc.cluster.local:9099"
  MCP_BASE_URL: "http://ai-nh-dev-private-ai-rag-nh-mcp-server.nh-addons.svc.cluster.local:8010"
  DEFAULT_MODEL: "private-ai-supervisor-agent"
  QDRANT_URL: "http://ai-nh-dev-private-ai-rag-qdrant.nh-addons.svc.cluster.local:6333"
  QDRANT_COLLECTION: "docs"
