project: nethopper-feature
destination:
  namespace: nethopper
  server: https://kubernetes.default.svc
loki: 
  source:
    targetRevision: 5.15.0
  values:
    loki:
      commonConfig:
        replication_factor: 1
      auth_enabled: false
      storage:
        type: 'filesystem'
    singleBinary:
      replicas: 1
      persistence:
        enableStatefulSetAutoDeletePVC: false
    monitoring:
      selfMonitoring:
        grafanaAgent:
          installOperator: false
promtail:
  source:
    targetRevision: 6.15.0
  values:
    config:
      enableTracing: false
datasources: []
  # - name: datasource-1
  #   url: http://datasource-1.default.svc.cluster.local
  # - name: datasource-2
  #   url: http://datasource-2.default.svc.cluster.local