apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "private-ai-websearch.searxng.fullname" . }}
  labels:
    {{- include "private-ai-websearch.labels" . | nindent 4 }}
    app.kubernetes.io/component: searxng
data:
  settings.yml: |
    {{- .Values.searxng.settings | nindent 4 }}
