{{- if .Values.worker.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nh-pai-data-service.fullname" . }}-worker
  labels:
    {{- include "nh-pai-data-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "nh-pai-data-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      {{- with .Values.worker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nh-pai-data-service.labels" . | nindent 8 }}
        app.kubernetes.io/component: worker
        {{- with .Values.worker.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nh-pai-data-service.serviceAccountName" . }}
      {{- with .Values.worker.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: worker
          {{- with .Values.worker.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.worker.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.worker.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.worker.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.worker.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.config.redisUrl }}
            - name: REDIS_URL
              value: {{ .Values.config.redisUrl | quote }}
            {{- end }}
            {{- if .Values.worker.env.workerConcurrency }}
            - name: WORKER_CONCURRENCY
              value: {{ .Values.worker.env.workerConcurrency | quote }}
            {{- end }}
            - name: AUTO_RUN_MIGRATIONS
              value: {{ .Values.autoRunMigrations | quote }}
            - name: POSTGRES_DATABASE
              value: {{ .Values.config.postgresDatabase }}
            - name: JUICEFS_S3_GATEWAY_ENDPOINT
              value: {{ .Values.config.juiceFsUrl }}
            - name: JUICEFS_S3_GATEWAY_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.juiceFsSecretName }}
                  key: minio-root-user
            - name: JUICEFS_S3_GATEWAY_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.juiceFsSecretName }}
                  key: minio-root-password
            - name: JUICEFS_S3_GATEWAY_VOLUME_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.juiceFsSecretName }}
                  key: name
            - name: JUICEFS_S3_GATEWAY_STORAGE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.juiceFsSecretName }}
                  key: storage
            - name: JUICEFS_S3_GATEWAY_BUCKET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.juiceFsSecretName }}
                  key: bucket
            - name: TOOLS_CONFIG
              value: {{ .Values.toolsConfig | quote }}
            {{- if .Values.worker.extraEnvVars }}
              {{- toYaml .Values.worker.extraEnvVars | nindent 12 }}
            {{- end }}
          envFrom:
          {{- if .Values.global.extraEnvVarsCM }}
            - configMapRef:
                name: {{ .Values.global.extraEnvVarsCM }}
          {{- end }}
          {{- if .Values.global.extraEnvVarsSecret }}
            - secretRef:
                name: {{ .Values.global.extraEnvVarsSecret }}
          {{- end }}
      {{- with .Values.worker.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
