apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "private-ai-storage-ui.fullname" . }}
  labels:
    {{- include "private-ai-storage-ui.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "private-ai-storage-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "private-ai-storage-ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "private-ai-storage-ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }} # 3000, Not service.port!
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS_BASE64
              valueFrom:
                secretKeyRef:
                  name: google-service-account-credentials
                  key: GOOGLE_APPLICATION_CREDENTIALS_BASE64   # the Secret key
            - name: GCS_BUCKET_NAME # Environment variable name
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.private-ai-storage-ui.sharedConfigMap }}
                  key: GCS_BUCKET_NAME # The key inside the config map
          # envFrom:
          #   - configMapRef:
          #     name: {{ .Values.private-ai-storage-ui.sharedConfigMap }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
