apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gdrive-gcs-sync.fullname" . }}
  labels:
    {{- include "gdrive-gcs-sync.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gdrive-gcs-sync.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gdrive-gcs-sync.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gdrive-gcs-sync.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{ if .Values.env.GCS_BUCKET_NAME }}
            - name: GCS_BUCKET_NAME
              value: {{ .Values.env.GCS_BUCKET_NAME }}
          {{ end }}
          {{ if .Values.env.DRIVE_FOLDER_ID }}
            - name: DRIVE_FOLDER_ID
              value: {{ .Values.env.DRIVE_FOLDER_ID }}
          {{ end }}
          {{ if .Values.env.GOOGLE_API_SCOPES }}
            - name: GOOGLE_API_SCOPES
              value: {{ .Values.env.GOOGLE_API_SCOPES }}
          {{ end }}
          {{ if .Values.global.googleApplicationCredentialsSecretRef }}
            - name: GOOGLE_APPLICATION_CREDENTIALS_BASE64
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.googleApplicationCredentialsSecretRef }}
                  key: GOOGLE_APPLICATION_CREDENTIALS_BASE64
          {{ end }}
          {{ if .Values.env.ALLOWED_EXTENSIONS }}
            - name: ALLOWED_EXTENSIONS
              value: {{ .Values.env.ALLOWED_EXTENSIONS }}
          {{ end }}
          {{- if .Values.extraEnvVars }}
            {{- toYaml .Values.extraEnvVars | nindent 12 }}
          {{- end }}
          envFrom:
          {{- if .Values.global.extraEnvVarsCM }}
            - configMapRef:
                name: {{ .Values.global.extraEnvVarsCM }}
          {{- end }}
          {{- if .Values.global.extraEnvVarsSecret }}
            - secretRef:
                name: {{ .Values.global.extraEnvVarsSecret }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
