apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
spec:
  destination:
    name: ''
    namespace: {{ .Values.destination.namespace }}
    server: {{ .Values.destination.server }}
  source:
    path: ''
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: {{ .Values.loki.source.targetRevision }}
    chart: loki
    helm:
      values: |-
        loki:
          loki:
            commonConfig:
              replication_factor: 1
            auth_enabled: false
            storage:
              type: 'filesystem'
          singleBinary:
            replicas: 1
  sources: []
  project: {{ .Values.project }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: false