apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-loki
spec:
  destination:
    name: ''
    namespace: {{ .Values.destination.namespace }}
    server: {{ .Values.destination.server }}
  source:
    path: ''
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: {{ .Values.loki.source.targetRevision }}
    chart: loki
    helm:
      values: |-
        loki:
          commonConfig:
            replication_factor: 1
          auth_enabled: false
          storage:
            type: 'filesystem'
        singleBinary:
          replicas: 1
        monitoring:
          selfMonitoring:
            grafanaAgent:
              installOperator: false
  sources: []
  project: {{ .Values.project }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - Replace=true
      - PruneLast=true